# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-09-06 17:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_auto_20180905_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='produccion',
            name='m_apellido_m',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='produccion',
            name='m_apellido_p',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='produccion',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 6, 17, 37, 11, 398757), editable=False, help_text='Fecha de recepci\xf3n de la llamada (No se puede modificar)'),
        ),
    ]
