# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-09-24 21:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0079_auto_20180924_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produccion',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 24, 16, 4, 54, 603192), editable=False, help_text='Fecha de recepci\xf3n de la llamada (No se puede modificar)'),
        ),
        migrations.AlterField(
            model_name='produccion',
            name='hora_instalacion',
            field=models.TimeField(blank=True, default=datetime.datetime(2018, 9, 24, 16, 4, 54, 605728), editable=False, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='produccion',
            name='marca_vehiculo',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='produccion',
            name='modelo',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
