# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-09-24 21:26
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0081_auto_20180924_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produccion',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 24, 16, 26, 25, 593712), editable=False, help_text='Fecha de recepci\xf3n de la llamada (No se puede modificar)'),
        ),
        migrations.AlterField(
            model_name='produccion',
            name='hora_instalacion',
            field=models.TimeField(blank=True, default=datetime.datetime(2018, 9, 24, 16, 26, 25, 596009), editable=False, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='produccion',
            name='marca_producto',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='produccion',
            name='modelo_bateria',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='produccion',
            name='usuario',
            field=models.ForeignKey(blank=True, help_text='Usuarios', max_length=1000, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='_modelo', to=settings.AUTH_USER_MODEL),
        ),
    ]
