# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-09-24 23:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0087_auto_20180924_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produccion',
            name='almacen',
            field=models.ForeignKey(blank=True, max_length=1000, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='_nombre', to='app.Almacen'),
        ),
        migrations.AlterField(
            model_name='produccion',
            name='atiende',
            field=models.ForeignKey(blank=True, max_length=1000, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='_nombre', to='app.Atiende'),
        ),
        migrations.AlterField(
            model_name='produccion',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 24, 18, 19, 30, 325911), editable=False, help_text='Fecha de recepci\xf3n de la llamada (No se puede modificar)'),
        ),
        migrations.AlterField(
            model_name='produccion',
            name='hora_instalacion',
            field=models.TimeField(blank=True, default=datetime.datetime(2018, 9, 24, 18, 19, 30, 328062), editable=False, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='produccion',
            name='status',
            field=models.ForeignKey(blank=True, max_length=1000, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='_nombre', to='app.Status'),
        ),
    ]
