# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-09-24 23:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0079_auto_20180924_1420'),
        ('app', '0088_auto_20180924_1819'),
    ]

    operations = [
    ]
