# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-09-25 20:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0091_auto_20180924_1830'),
        ('app', '0090_auto_20180925_1442'),
    ]

    operations = [
    ]
