# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-09-28 16:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0092_merge'),
        ('app', '0093_auto_20180925_1800'),
    ]

    operations = [
    ]
