# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-09-28 21:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0097_auto_20180928_1604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produccion',
            name='serie',
        ),
        migrations.AlterField(
            model_name='produccion',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 28, 16, 41, 1, 746544), editable=False, help_text='Fecha de recepci\xf3n de la llamada (No se puede modificar)'),
        ),
        migrations.AlterField(
            model_name='produccion',
            name='hora_instalacion',
            field=models.TimeField(blank=True, default=datetime.datetime(2018, 9, 28, 16, 41, 1, 749298), editable=False, max_length=1000, null=True),
        ),
    ]
