# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-09-28 22:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0094_merge'),
        ('app', '0098_auto_20180928_1641'),
    ]

    operations = [
    ]
