# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-10-02 19:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0106_auto_20181002_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produccion',
            name='anio',
            field=models.ForeignKey(blank=True, help_text='Anio', max_length=1000, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='_nombre', to='app.Anio_v'),
        ),
        migrations.AlterField(
            model_name='produccion',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 2, 14, 8, 27, 39639), editable=False, help_text='Fecha de recepci\xf3n de la llamada (No se puede modificar)'),
        ),
        migrations.AlterField(
            model_name='produccion',
            name='hora_instalacion',
            field=models.TimeField(blank=True, default=datetime.datetime(2018, 10, 2, 14, 8, 27, 41858), editable=False, max_length=1000, null=True),
        ),
    ]
