# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-10-03 20:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0099_merge'),
        ('app', '0132_auto_20181003_1526'),
    ]

    operations = [
    ]
