# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-10-04 16:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0136_auto_20181004_1140'),
        ('app', '0133_auto_20181004_1143'),
    ]

    operations = [
    ]
