# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-10-10 19:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0139_auto_20181009_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produccion',
            name='apellido_p',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Apellido Paterno'),
        ),
        migrations.AlterField(
            model_name='produccion',
            name='cliente',
            field=models.CharField(blank=True, help_text='Nombre del Cliente', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='produccion',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 10, 14, 19, 46, 824012), editable=False, help_text='Fecha de recepci\xf3n de la llamada (No se puede modificar)'),
        ),
        migrations.AlterField(
            model_name='produccion',
            name='hora_instalacion',
            field=models.TimeField(blank=True, default=datetime.datetime(2018, 10, 10, 14, 19, 46, 826014), editable=False, max_length=1000, null=True),
        ),
    ]
