# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-10-18 19:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0140_auto_20181004_1230'),
        ('app', '0145_auto_20181011_0858'),
    ]

    operations = [
    ]
