# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-18 13:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0146_merge_20181018_0734'),
        ('app', '0146_merge'),
    ]

    operations = [
    ]
