# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-11-09 19:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0158_auto_20181107_0257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produccion',
            name='motorisado',
        ),
        migrations.AlterField(
            model_name='produccion',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 9, 14, 35, 21, 194079), editable=False, help_text='Fecha de recepci\xf3n de la llamada (No se puede modificar)'),
        ),
    ]
