# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-11-15 17:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0162_auto_20181115_1236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pago',
            name='retiro',
        ),
        migrations.AlterField(
            model_name='produccion',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 15, 12, 38, 37, 615434), editable=False, help_text='Fecha de recepci\xf3n de la llamada (No se puede modificar)'),
        ),
    ]
