# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-11-16 15:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0163_auto_20181115_1238'),
        ('app', '0162_auto_20181115_1054'),
    ]

    operations = [
    ]
