# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-11-21 15:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0164_auto_20181121_0959'),
        ('app', '0164_merge_20181116_1051'),
    ]

    operations = [
    ]
